blank_issues_enabled: true
contact_links:
  - name: 📖 Documentation
    url: https://github.com/generalaction/emdash/blob/main/README.md
    about: Check the README for usage examples and documentation
